# Generated by Django 2.0 on 2017-12-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0003_auto_20171213_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='roles',
            field=models.CharField(blank=True, choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('DEAN', 'Dean')], max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('FEMALE', 'F'), ('MALE', 'M'), ('NONE', 'None')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
