# Generated by Django 2.0 on 2017-12-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0004_auto_20171213_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='degree',
            field=models.CharField(blank=True, choices=[('BBIT', 'Bachelor of Business Information technology'), ('BCOM', 'Bachelor of Commerce'), ('ACTUARIAL', 'Actuarial Science'), ('CIS', 'Computer Science')], max_length=30),
        ),
    ]
