# Generated by Django 2.0 on 2017-12-13 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0007_course_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='user',
        ),
    ]
