# Generated by Django 2.0 on 2017-12-13 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0009_auto_20171214_0033'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Program',
        ),
    ]
