# Generated by Django 2.0 on 2017-12-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0010_auto_20171214_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='courses',
            field=models.ManyToManyField(to='lecturer.Program'),
        ),
    ]
