# Generated by Django 2.0 on 2017-12-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0011_auto_20171214_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='modules',
            field=models.ManyToManyField(to='lecturer.Module'),
        ),
    ]
