# Generated by Django 2.0 on 2017-12-13 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0012_auto_20171214_0106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='courses',
            new_name='programs',
        ),
    ]
