# Generated by Django 2.0 on 2017-12-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0013_auto_20171214_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='roles',
            field=models.CharField(blank=True, choices=[('STUDENT', 'Student'), ('LECTURER', 'Lecturer'), ('DEAN', 'Dean')], max_length=30),
        ),
    ]
