# Generated by Django 2.0 on 2017-12-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0015_remove_profile_degree'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('modules', models.ManyToManyField(to='lecturer.Module')),
            ],
        ),
    ]
