# Generated by Django 2.0 on 2017-12-13 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0017_unit_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='user',
            new_name='lec',
        ),
    ]
