# Generated by Django 2.0 on 2017-12-13 22:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lecturer', '0018_auto_20171214_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='enrol_students',
            field=models.ManyToManyField(related_name='student', to=settings.AUTH_USER_MODEL),
        ),
    ]
