# Generated by Django 2.0 on 2017-12-13 22:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lecturer', '0019_unit_enrol_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='enrol_students',
        ),
        migrations.AddField(
            model_name='unit',
            name='sharing_modules',
            field=models.ManyToManyField(related_name='enrolled_module', to=settings.AUTH_USER_MODEL),
        ),
    ]
