# Generated by Django 2.0 on 2017-12-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0020_auto_20171214_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='sharing_modules',
            field=models.ManyToManyField(related_name='sharing_module', to='lecturer.Module'),
        ),
    ]
