# Generated by Django 2.0 on 2017-12-13 23:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lecturer', '0021_auto_20171214_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='modules',
        ),
        migrations.AddField(
            model_name='module',
            name='enrolled_students',
            field=models.ManyToManyField(related_name='enrolled_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
