# Generated by Django 2.0 on 2017-12-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0022_auto_20171214_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='exam_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='stop_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='venue',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
