# Generated by Django 2.0 on 2017-12-15 10:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lecturer', '0026_project_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='lec',
        ),
        migrations.AddField(
            model_name='unit',
            name='lec',
            field=models.ManyToManyField(null=True, related_name='lec', to=settings.AUTH_USER_MODEL),
        ),
    ]
