# Generated by Django 2.0 on 2017-12-15 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0029_auto_20171215_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
    ]
