# Generated by Django 2.0 on 2017-12-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0031_auto_20171223_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='class_day',
            field=models.CharField(blank=True, choices=[('SUNDAY', 'Sun'), ('MONDAY', 'Mon'), ('TUESDAY', 'Tue'), ('WEDNESDAY', 'Wed'), ('THURSDAY', 'Thurs'), ('FRIDAY', 'Fri'), ('SATURDAY', 'Sat')], max_length=50),
        ),
    ]
