# Generated by Django 2.0 on 2017-12-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0032_unit_class_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(choices=[('SUNDAY', 'Sun'), ('MONDAY', 'Mon'), ('TUESDAY', 'Tue'), ('WEDNESDAY', 'Wed'), ('THURSDAY', 'Thurs'), ('FRIDAY', 'Fri'), ('SATURDAY', 'Sat')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='unit',
            name='class_day',
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_days',
            field=models.ManyToManyField(to='lecturer.Days'),
        ),
    ]
