# Generated by Django 2.0 on 2017-12-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0033_auto_20171223_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='days',
            name='days',
            field=models.CharField(choices=[('SUNDAY', 'Sun'), ('MONDAY', 'Mon'), ('TUESDAY', 'Tue'), ('WEDNESDAY', 'Wed'), ('THURSDAY', 'Thurs'), ('FRIDAY', 'Fri'), ('SATURDAY', 'Sat')], max_length=30),
        ),
    ]
