# Generated by Django 2.0 on 2017-12-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0034_auto_20171223_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='stop_time',
            field=models.TimeField(null=True),
        ),
    ]
