# Generated by Django 2.0 on 2017-12-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0035_auto_20171223_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assessment_type',
            field=models.ForeignKey(null=True, on_delete='models.CASCADE', related_name='assessment', to='lecturer.Assessment'),
        ),
    ]
