# Generated by Django 2.0 on 2017-12-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0036_project_assessment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='submissions',
            field=models.ManyToManyField(blank=True, related_name='submitted_projects', to='student.Submission'),
        ),
    ]
