# Generated by Django 2.0 on 2017-12-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0039_auto_20171223_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='additional_notes',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
