# Generated by Django 2.0 on 2017-12-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0040_auto_20171223_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='due_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
