# Generated by Django 2.0 on 2017-12-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0041_project_due_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='unit',
            field=models.ForeignKey(null=True, on_delete='models.CASCADE', related_name='unit', to='lecturer.Unit'),
        ),
    ]
